import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "@/services/auth/auth-provider";
import DomainProvider from "@/services/domains/domains-provider";
import { MyDomainsProvider } from "@/services/domains/my-domains-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <MyDomainsProvider>
            <DomainProvider>
              {/* Header */}
              <Navbar />

              {/* Main Content: Flex-grow ensures it stretches */}
              <main className="flex-grow flex flex-col">
                {children}
              </main>

              {/* Footer: Pushed to the bottom */}
              <Footer />
            </DomainProvider>
          </MyDomainsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
